# Awọn iru ẹrọ awoṣe inawo ti o ni atilẹyin wọnyi ni:

github: # Rọpo pẹlu to 4 orukọ olumulo ti o ni agbara GitHub Sponsors, e.g., [olumulo1, olumulo2]
patreon: # Rọpo pẹlu orukọ olumulo Patreon kan ṣoṣo
open_collective: # Rọpo pẹlu orukọ olumulo Open Collective kan ṣoṣo
ko_fi: # Rọpo pẹlu orukọ olumulo Ko-fi kan ṣoṣo
tidelift: # Rọpo pẹlu orukọ iru ẹrọ Tidelift/package kan ṣoṣo, e.g., npm/babel
custom: https://www.buymeacoffee.com/PtZnDSaEo
